name: Check Formatting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.11
      
    - name: Create and Activate Virtual Environment
      run: python -m venv venv && source venv/bin/activate
      
    - name: Upgrade pip
      run: pip install --upgrade pip
      
    - name: Install Cython
      run: pip install Cython
      
    - name: Install Dependencies
      run: pip install -r requirements_ubuntu.txt
      
    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black .

  windows_build:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
          python-version: 3.11
      
    - name: Install Dependencies
      run: pip install -r requirements_windows.txt

    - name: Install pywin32
      run: pip install pywin32
      
    - name: Install Black
      run: pip install black

    - name: Run Black
      run: black .
